CREATE TABLE IF NOT EXISTS kudos (
    id INTEGER PRIMARY KEY,
    from_user_id VARCHAR(50) NOT NULL,
    is_anonymous TINYINT(1) NOT NULL DEFAULT 0,
    message TEXT,
    to_user_id VARCHAR(50) NOT NULL,
    is_public TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shared_at DATETIME DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS kudos (shared_at)
